/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package brickbreaker;

import java.awt.Color;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wwwsh
 */
public class DifficultMenu extends javax.swing.JFrame {

    String username;
    private int totalBricks;
    private int row;
    private int col;
    private int delay;
    private String difLevel = "null";
    private int numPlayer = 0;
    private ArrayList<String> err = new ArrayList<>();
    private Color[] brickColors;
    private Color ballColor;
    /**
     * Creates new form DifficultMenu
     */
    
    public DifficultMenu() {}
    
    public DifficultMenu(String username) {
        this.username = username;
        String path = new File("src/Image/bg2.gif").getAbsolutePath();
        BackgroundPanel backgroundPanel = new BackgroundPanel(path);
        setContentPane(backgroundPanel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EASYBTN = new javax.swing.JButton();
        MEDIUMBTN = new javax.swing.JButton();
        HARDBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ONEBTN = new javax.swing.JButton();
        TWOBTN = new javax.swing.JButton();
        okBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        purpleBtn = new javax.swing.JButton();
        blueBtn = new javax.swing.JButton();
        greenBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Difficult");
        setLocation(new java.awt.Point(500, 200));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setText("SELECT SETTING GAME");

        EASYBTN.setBackground(new java.awt.Color(204, 0, 204));
        EASYBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        EASYBTN.setForeground(new java.awt.Color(255, 255, 255));
        EASYBTN.setText("EASY");
        EASYBTN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        EASYBTN.setBorderPainted(false);
        EASYBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EASYBTNActionPerformed(evt);
            }
        });

        MEDIUMBTN.setBackground(new java.awt.Color(153, 0, 153));
        MEDIUMBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        MEDIUMBTN.setForeground(new java.awt.Color(255, 255, 255));
        MEDIUMBTN.setText("MEDIUM");
        MEDIUMBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIUMBTNActionPerformed(evt);
            }
        });

        HARDBTN.setBackground(new java.awt.Color(102, 0, 102));
        HARDBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        HARDBTN.setForeground(new java.awt.Color(255, 255, 255));
        HARDBTN.setText("HARD");
        HARDBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARDBTNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Difficult Level");

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number OF PLAYER");

        ONEBTN.setBackground(new java.awt.Color(204, 0, 204));
        ONEBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        ONEBTN.setForeground(new java.awt.Color(255, 255, 255));
        ONEBTN.setText("1");
        ONEBTN.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ONEBTN.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ONEBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ONEBTNActionPerformed(evt);
            }
        });

        TWOBTN.setBackground(new java.awt.Color(153, 0, 153));
        TWOBTN.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        TWOBTN.setForeground(new java.awt.Color(255, 255, 255));
        TWOBTN.setText("2");
        TWOBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TWOBTNActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        okBtn.setForeground(new java.awt.Color(153, 0, 153));
        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(204, 0, 204));
        backBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELECT COLOR THEME");

        purpleBtn.setBackground(new java.awt.Color(153, 0, 153));
        purpleBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 28)); // NOI18N
        purpleBtn.setForeground(new java.awt.Color(255, 255, 255));
        purpleBtn.setText("PURPLE");
        purpleBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        purpleBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        purpleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleBtnActionPerformed(evt);
            }
        });

        blueBtn.setBackground(new java.awt.Color(0, 102, 204));
        blueBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 28)); // NOI18N
        blueBtn.setForeground(new java.awt.Color(255, 255, 255));
        blueBtn.setText("BLUE");
        blueBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        blueBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        blueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBtnActionPerformed(evt);
            }
        });

        greenBtn.setBackground(new java.awt.Color(0, 153, 153));
        greenBtn.setFont(new java.awt.Font("Showcard Gothic", 0, 28)); // NOI18N
        greenBtn.setForeground(new java.awt.Color(255, 255, 255));
        greenBtn.setText("green");
        greenBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        greenBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        greenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(purpleBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(EASYBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ONEBTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TWOBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MEDIUMBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HARDBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(greenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EASYBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEDIUMBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HARDBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TWOBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ONEBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purpleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EASYBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EASYBTNActionPerformed
        // TODO add your handling code here:
        this.totalBricks = 20;
        this.row = 2;
        this.col = 10;
        this.delay = 11;
        this.difLevel = "Easy";
        
        EASYBTN.setBackground(Color.WHITE);
        EASYBTN.setForeground(Color.black);
        MEDIUMBTN.setBackground(new Color(153, 0, 153));
        MEDIUMBTN.setForeground(Color.white);
        HARDBTN.setBackground(new Color(102, 0, 102));
        HARDBTN.setForeground(Color.white);  
    }//GEN-LAST:event_EASYBTNActionPerformed

    private void MEDIUMBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIUMBTNActionPerformed
        // TODO add your handling code here:
        this.totalBricks = 30;
        this.row = 3;
        this.col = 10;
        this.delay = 8;
        this.difLevel = "Medium";
        
        EASYBTN.setBackground(new Color(204, 0, 204));
        EASYBTN.setForeground(Color.white);
        MEDIUMBTN.setBackground(Color.WHITE);
        MEDIUMBTN.setForeground(Color.black);
        HARDBTN.setBackground(new Color(102, 0, 102));
        HARDBTN.setForeground(Color.white);
    }//GEN-LAST:event_MEDIUMBTNActionPerformed

    private void HARDBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARDBTNActionPerformed
        // TODO add your handling code here:
        this.totalBricks = 40;
        this.row = 4;
        this.col = 10;
        this.delay = 4;
        this.difLevel = "Hard";
        
        EASYBTN.setBackground(new Color(204, 0, 204));
        EASYBTN.setForeground(Color.white);
        MEDIUMBTN.setBackground(new Color(153, 0, 153));
        MEDIUMBTN.setForeground(Color.white);
        HARDBTN.setBackground(Color.white);
        HARDBTN.setForeground(Color.black);
    }//GEN-LAST:event_HARDBTNActionPerformed

    private void ONEBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ONEBTNActionPerformed
        // TODO add your handling code here:
        this.numPlayer = 1;
        ONEBTN.setBackground(Color.white);
        ONEBTN.setForeground(Color.black);
        TWOBTN.setBackground(new Color(153, 0, 153));
        TWOBTN.setForeground(Color.white);
    }//GEN-LAST:event_ONEBTNActionPerformed

    private void TWOBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TWOBTNActionPerformed
        // TODO add your handling code here:
        this.numPlayer = 2;
        ONEBTN.setBackground(new Color(204, 0, 204));
        ONEBTN.setForeground(Color.white);
        TWOBTN.setBackground(Color.white);
        TWOBTN.setForeground(Color.black);
    }//GEN-LAST:event_TWOBTNActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        // TODO add your handling code here:
        if(difLevel.equals("null"))
        {
            err.add("Vui lòng chọn độ khó");
        }
        if(numPlayer == 0)
        {
            err.add("Vui lòng chọn số người chơi");
        }
        if(!err.isEmpty())
        {
            JOptionPane.showMessageDialog(null, err.toArray());
            err.clear();
        }
        else{
            Gameplay game = new Gameplay(totalBricks, row, col, delay, username, difLevel, numPlayer, brickColors, ballColor);
            game.setVisible(true);
            this.dispose();
        }    
    }//GEN-LAST:event_okBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        MenuGame menu = null;
        try {
            menu = new MenuGame(this.username);
        } catch (SQLException ex) {
            Logger.getLogger(DifficultMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void purpleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purpleBtnActionPerformed
        // TODO add your handling code here:
        Color[] purpleBricks = {new Color(255, 131, 250), new Color(224, 102, 255)};
        this.brickColors = purpleBricks;
        this.ballColor = new Color(255, 131, 250);
        
        purpleBtn.setBackground(Color.white);
        purpleBtn.setForeground(new Color(153, 0, 153));
        blueBtn.setBackground(new Color(0,102,204));
        blueBtn.setForeground(Color.white);
        greenBtn.setBackground(new Color(0, 153, 153));
        greenBtn.setForeground(Color.white);
    }//GEN-LAST:event_purpleBtnActionPerformed

    private void blueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBtnActionPerformed
        // TODO add your handling code here:
        Color[] blueBricks = {new Color(72, 118, 255), new Color(58, 95, 205)};
        this.brickColors = blueBricks;
        this.ballColor = new Color(0, 191, 255);
        
        purpleBtn.setBackground(new Color(153, 0, 153));
        purpleBtn.setForeground(Color.white);
        blueBtn.setBackground(Color.white);
        blueBtn.setForeground(new Color(0,102,204));
        greenBtn.setBackground(new Color(0, 153, 153));
        greenBtn.setForeground(Color.white);
    }//GEN-LAST:event_blueBtnActionPerformed

    private void greenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBtnActionPerformed
        // TODO add your handling code here:
        Color[] greenBricks = {new Color(118, 238, 0), new Color(102, 205, 0)};
        this.brickColors = greenBricks;
        this.ballColor = new Color(0, 255, 0);
        
        purpleBtn.setBackground(new Color(153, 0, 153));
        purpleBtn.setForeground(Color.white);
        blueBtn.setBackground(new Color(0,102,204));
        blueBtn.setForeground(Color.white);
        greenBtn.setBackground(Color.white);
        greenBtn.setForeground(new Color(0, 153, 153));
    }//GEN-LAST:event_greenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DifficultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DifficultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DifficultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DifficultMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DifficultMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EASYBTN;
    private javax.swing.JButton HARDBTN;
    private javax.swing.JButton MEDIUMBTN;
    private javax.swing.JButton ONEBTN;
    private javax.swing.JButton TWOBTN;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton blueBtn;
    private javax.swing.JButton greenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okBtn;
    private javax.swing.JButton purpleBtn;
    // End of variables declaration//GEN-END:variables
}
